### PR TITLE
AA Test

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by adriencaccia** [comment]
Hey @mdboom, in order for the benchmarks to be registered, you need to call [`lib.dump_stats_at(uri)`](https://github.com/CodSpeedHQ/pytest-codspeed/blob/90e639bae554306ae6c4c0769e3c3efba7ef2e00/src/pytest_codspeed/plugin.py#L200), where `uri` is a string containing the benchmark's uri, like: `path/to/definition/file::benchmark-name`, for example  `tests/benchmarks/test_bench_fibo.py::test_iterative_fibo_10`.

You can try to call it here: https://github.com/mdboom/pyperformance/commit/9234f4d0a75000c1f1b11e187a133ae4949583c6#diff-ef2cbcccccf978441b4d1bb0eeb21883285cc07d766b546ec7ca5d0942f8755eR637

**Comment by mdboom** [comment]
Thanks!  Just noticed that and trying again ;)

**Comment by mdboom** [comment]
@adriencaccia: So I think I have results published from this branch correctly, but it's not finding the baseline results from main.  I manually triggered them [here](https://github.com/mdboom/pyperf-codspeed/actions/runs/9162601620), but is there something more I need to do?

**Comment by adriencaccia** [comment]
> @adriencaccia: So I think I have results published from this branch correctly, but it's not finding the baseline results from main. I manually triggered them [here](https://github.com/mdboom/pyperf-codspeed/actions/runs/9162601620), but is there something more I need to do?

There was an error on our backend during the processing of both the run on `master` and this pull request. So the runs are not persisted on our end.
I tracked down the bug, and it is because there are multiple `codspeed.dump_stats_at("deltablue".encode("ascii"))` happening during a single run.

Can you ensure that this line is called exactly once with the same argument during the run?

In our integrations, we always made sure to have a single `dump_stats_at` for each `uri`, so we did not handle the case with multiple calls

**Comment by mdboom** [comment]
> In our integrations, we always made sure to have a single dump_stats_at for each uri, so we did not handle the case with multiple calls

Yes, that should be easily possible with the "hack" I'm testing now.  In general with pyperf, it can run benchmarks in a subprocess, so (maybe) that will be more difficult.  But I'll just keep that in mind for when I get there.

**Pull request closed without merging**
